{{- if .Values.core.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "coreauth.core.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coreauth.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "coreauth.core.fullname" . }}
  minReplicas: {{ .Values.core.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.core.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.core.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.core.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.core.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.core.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
